### ISSUE TITLE
SVT: server.xml feature invalid suggestion from VSCode Liberty Tools

### ISSUE THREAD

**Issue by hanczaryk** [OpenLiberty/liberty-tools-vscode#248] opened 2023-05-08 19:23 UTC
SVT: server.xml feature invalid suggestion from VSCode Liberty Tools

I setup VSCode 1.78.0 on Windows.  I installed the extension (liberty-dev-vscode-ext-0.1.13-SNAPSHOT.vsix) using CLI

```
C:\brian\was\VSCode\VSCode-win32-x64-1.78.0\bin>code --install-extension ..\..\ext\liberty-dev-vscode-ext-0.1.13-SNAPSHOT.vsix --force
Installing extensions...
(node:16924) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
Extension 'liberty-dev-vscode-ext-0.1.13-SNAPSHOT.vsix' was successfully installed.
```

I've setup my SVT Application (MPProShop).  

The VSCode server.xml feature suggestions don't look correct like I would expect.  Here is a screenshot where I would expect the feature suggestion to be servlet-X.X based on my typing of 'servl'

![image](https://media.github.ibm.com/user/26521/files/1db6fa81-d7fc-4271-b8b6-582f1e8bc2f1)

When I click out of the VSCode into a different window, like a browser, and click back in VSCode, then it showed me what should be the proper suggestions.

![image](https://media.github.ibm.com/user/26521/files/109f30c1-9a86-4c11-88b1-727ada31543a)

If I delete all the text between the feature tags and start typing again, it shows the incorrect suggestions, this time for 'serv'.

![image](https://media.github.ibm.com/user/26521/files/6d24ed07-e18b-466d-aeb0-820b88995ef3)

**Comment by TrevCraw** [comment] 2023-05-08 19:42
Same as https://github.com/OpenLiberty/liberty-tools-vscode/issues/194

**Comment by cherylking** [comment] 2023-05-12 13:50
If this is a duplicate of #194, should we close this one so we are not tracking multiple issues for one problem?

**Comment by TrevCraw** [comment] 2023-05-12 21:26
Closing as duplicate of #194

**Closed by TrevCraw** 2023-05-12 21:26 UTC
Labels: bug, SVT
