### ISSUE TITLE
Support for Java 21

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/liberty-tools-vscode#335] opened 2024-06-19 16:14 UTC
VS Code supports the use of Java 21.  Filing this issue to track corresponding support in Liberty Tools.

First step is to test with Java 21 and see how things go.

- [x] #346

**Comment by gilbysunil14** [comment] 2024-10-15 15:51
The following steps done to check the support for java 21 in liberty tool for vs code:

1. Set the `JAVA_HOME` path to point to Java 21.
2. Performed FVT testing for both maven and gradle.
3. Found the following issues #345 and #346.

**Comment by gilbysunil14** [comment] 2024-10-22 08:22
Upon investigation, found out that the issues #345 and #346 were not issues that caused by the Java 21 support. Hence closing this issue.

**Closed** 2024-10-22 15:11 UTC
Labels: high priority
