### ISSUE TITLE
Completion is not showing in microprofile-config.properties file 

### ISSUE THREAD

**Issue by Rahul-Biju** [OpenLiberty/liberty-tools-vscode#289] opened 2023-09-15 09:36 UTC
Issue found in Manual Regression Testing.

When we do gradle test in both Windows and linux for the snapshot : open-liberty.liberty-dev-vscode-ext-23.0.9-SNAPSHOT. We are not getting suggestion/completion for “mp.jwt”

Windows -> OS version : Windows 10 Enterprise 64-bit operating system, x64-based processor
Windows -> vscode version : 1.82.1

Linux -> Redhat Linux OS version : 9.2
Linux ->  vscode version : 1.82.0

<img width="1062" alt="Screenshot 2023-09-15 at 1 04 51 PM" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/166a69a0-d642-4e6f-969f-21d5810f5a7e">

<img width="1179" alt="Screenshot 2023-09-15 at 2 48 46 PM" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/d6f497e3-4652-4d55-89b2-8b3ddb7e6afb">

**Comment by TrevCraw** [comment] 2023-09-15 13:45
Duplicate of https://github.com/OpenLiberty/liberty-tools-vscode/issues/249

However, #249 seems to show that when located at `resources/META-INF/microprofile-config.properties`, suggestions are provided - however, this update seems to show that suggestions are not provided at that location either.

**Comment by TrevCraw** [comment] 2023-09-15 13:45
Duplicate of https://github.com/OpenLiberty/liberty-tools-vscode/issues/249

However, #249 seems to show that when located at `resources/META-INF/microprofile-config.properties`, suggestions are provided - however, this update seems to show that suggestions are not provided at that location either.

**Closed by TrevCraw** 2023-09-15 13:45 UTC
Labels: duplicate
