### ISSUE TITLE
Exception throwing in Language Server for JakartaEE and Language Server for Liberty in Java 21

### ISSUE THREAD

**Issue by gilbysunil14** [OpenLiberty/liberty-tools-vscode#346] opened 2024-10-15 09:02 UTC
The following exception is thrown in Language support for JakartaEE and Language support for Liberty while using Java 21 as the runtime environment. To replicate the issue follow the below steps:

1. Create a new open liberty project using [https://openliberty.io/start/](url) by giving Java SE version as 21.
2. Open this project in the VS code.
3. Take the output tab and select Language support for JakkartaEE or Language support for Liberty. There you could find the following exception.

https://github.com/user-attachments/assets/d67080e0-2527-473e-ae66-04d25da38877

```
Oct 15, 2024 2:44:21 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "$/setTrace",
  "params": {
    "value": "off"
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at io.openliberty.tools.langserver.common.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:154)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1595)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.services.LanguageServer.setTrace(LanguageServer.java:125)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 14 more
```

**Comment by gilbysunil14** [comment] 2024-10-17 06:05
Upon analysis found out that the issue is coming from lsp4jakarta.

**Comment by TrevCraw** [comment] 2024-10-21 21:21
Closing as duplicate of https://github.com/OpenLiberty/liberty-tools-vscode/issues/207

**Closed by TrevCraw** 2024-10-21 21:21 UTC
Labels: duplicate
